version: "3"

services:
  database:
    image: postgres:13.4-alpine
    volumes:
      - database_data:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./project:/app

volumes:
  database_data:
